import type { StudySession } from './types';

// Mock sessions around San Francisco (default center)
const baseDate = new Date('2024-01-15T10:00:00'); // Fixed base date
export const mockSessions: StudySession[] = [
  {
    id: '1',
    title: 'Deep Focus: Algorithms',
    subject: 'Computer Science',
    lat: 37.7849,
    lng: -122.4094,
    startTime: baseDate,
    duration: 120,
    participants: 12,
    maxParticipants: 20,
    type: 'silent',
    status: 'live',
  },
  {
    id: '2',
    title: 'Calculus Study Group',
    subject: 'Mathematics',
    lat: 37.7799,
    lng: -122.4144,
    startTime: new Date(baseDate.getTime() + 15 * 60 * 1000), // 15 min from base
    duration: 90,
    participants: 8,
    maxParticipants: 15,
    type: 'discussion',
    status: 'starting-soon',
  },
  {
    id: '3',
    title: 'MCAT Prep Session',
    subject: 'Medicine',
    lat: 37.7919,
    lng: -122.4014,
    startTime: baseDate,
    duration: 180,
    participants: 6,
    maxParticipants: 10,
    type: 'exam-prep',
    status: 'live',
  },
  {
    id: '4',
    title: 'Physics Problem Solving',
    subject: 'Physics',
    lat: 37.7749,
    lng: -122.4194,
    startTime: new Date(baseDate.getTime() - 3 * 60 * 60 * 1000), // 3 hours before base
    duration: 120,
    participants: 15,
    maxParticipants: 15,
    type: 'silent',
    status: 'finished',
  },
  {
    id: '5',
    title: 'Machine Learning Workshop',
    subject: 'AI/ML',
    lat: 37.7879,
    lng: -122.3964,
    startTime: new Date(baseDate.getTime() + 30 * 60 * 1000), // 30 min from base
    duration: 150,
    participants: 18,
    maxParticipants: 25,
    type: 'discussion',
    status: 'starting-soon',
  },
  {
    id: '6',
    title: 'Organic Chemistry Review',
    subject: 'Chemistry',
    lat: 37.7699,
    lng: -122.4294,
    startTime: baseDate,
    duration: 90,
    participants: 4,
    maxParticipants: 12,
    type: 'silent',
    status: 'live',
  },
  {
    id: '7',
    title: 'GRE Verbal Practice',
    subject: 'Test Prep',
    lat: 37.7829,
    lng: -122.4244,
    startTime: baseDate,
    duration: 60,
    participants: 9,
    maxParticipants: 15,
    type: 'exam-prep',
    status: 'live',
  },
  {
    id: '8',
    title: 'Data Structures Sprint',
    subject: 'Computer Science',
    lat: 37.7769,
    lng: -122.4044,
    startTime: new Date(baseDate.getTime() - 2 * 60 * 60 * 1000),
    duration: 90,
    participants: 20,
    maxParticipants: 20,
    type: 'silent',
    status: 'finished',
  },
];

// Mock live count that can be connected to API later
export const getMockLiveCount = (): number => {
  return 1284 + Math.floor(Math.random() * 50);
};
